#!/usr/bin/env node
/**
 * Generates the installable Claude Code and Cursor plugins (skill + agent +
 * command + MCP config + manifest) under plugins/claude/ and plugins/cursor/
 * from the canonical prompt/server sources in mcps/newrelic and the repo's own
 * package.json / .mcp.json, so the two plugin trees never drift out of sync
 * with each other or with the MCP server they wrap.
 *
 * Run: npm run build:plugins
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { commercePrompt } from '../mcps/newrelic/prompts/commerce.js';
import { securityAgentPrompt } from '../mcps/newrelic/prompts/security.js';

const pluginsDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(pluginsDir, '..');

const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));
const rootMcp = JSON.parse(readFileSync(join(repoRoot, '.mcp.json'), 'utf8'));

// Must match the plugin name in .claude-plugin/marketplace.json and
// .cursor-plugin/marketplace.json at the repo root.
const PLUGIN_NAME = 'adobe-commerce-tools';
const PLUGIN_DESCRIPTION =
  'New Relic observability and security analysis for Adobe Commerce: NRQL skill, security-analyst agent, /nrql command, and MCP server.';
const PLUGIN_AUTHOR = 'B G Kavinga';

const GENERATED_NOTICE =
  '<!-- Generated by plugins/build.ts — do not edit by hand. Run `npm run build:plugins`. -->\n\n';

function writeGenerated(target: string, relPath: string, content: string): void {
  const fullPath = join(pluginsDir, target, relPath);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content, 'utf8');
  console.log(`plugins/${target}/${relPath}`);
}

function markdownFile(fields: Record<string, string>, body: string): string {
  const frontmatter = Object.entries(fields)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join('\n');
  return `---\n${frontmatter}\n---\n\n${GENERATED_NOTICE}${body.trim()}\n`;
}

// Skill: model-invoked reference knowledge. The description states when to
// use it so the host agent triggers it reliably.
const skillMd = markdownFile(
  {
    name: 'newrelic-commerce',
    description:
      'Use when writing or running NRQL queries against New Relic for Adobe Commerce projects — logs, Fastly/CDN logs, transactions, APM errors, Redis, MySQL, Elasticsearch, or RabbitMQ data. Covers resolving project IDs to account IDs, per-entity WHERE filters, and mandatory field discovery.',
  },
  commercePrompt,
);

// Agent: isolated-context subagent for the multi-step security investigation
// workflow. The description tells the host when to delegate to it.
const agentMd = markdownFile(
  {
    name: 'newrelic-security',
    description:
      'Security analyst for Adobe Commerce projects on New Relic. Use when an attack is suspected or reported — brute force, credential stuffing, SQL injection, XSS, DDoS, scraping, carding, admin probing, or API abuse — to investigate with NRQL and report findings with mitigations.',
  },
  securityAgentPrompt,
);

// Command: explicit user-triggered entry point with arguments.
const commandMd = markdownFile(
  {
    name: 'nrql',
    description: 'Run an ad-hoc NRQL query against New Relic for an Adobe Commerce project.',
  },
  [
    'Run the NRQL query below against New Relic.',
    '',
    '1. If given an Adobe Commerce project ID instead of an account ID, call `get_account_id_by_project_id` first and use the returned account ID.',
    '2. Execute the query with the `execute_nrql` tool.',
    '3. Summarize the result set: row count, key fields, and any errors.',
    '',
    'For field-discovery rules and standard Adobe Commerce entity filters, invoke the `newrelic-commerce` skill first.',
    '',
    'Query:',
    '$ARGUMENTS',
  ].join('\n'),
);

// Take command/args from the root .mcp.json but always emit env-var
// interpolation so installed plugins read the user's environment instead of
// the repo's placeholder values.
const mcpJson = `${JSON.stringify(
  {
    mcpServers: {
      newrelic: {
        ...rootMcp.mcpServers.newrelic,
        env: {
          NEW_RELIC_API_KEY: '${NEW_RELIC_API_KEY}',
          NEW_RELIC_REGION: '${NEW_RELIC_REGION:-us}',
        },
      },
    },
  },
  null,
  2,
)}\n`;

const manifestJson = `${JSON.stringify(
  {
    name: PLUGIN_NAME,
    description: PLUGIN_DESCRIPTION,
    version: pkg.version,
    author: { name: PLUGIN_AUTHOR },
  },
  null,
  2,
)}\n`;

const targets = [
  { dir: 'claude', manifestPath: '.claude-plugin/plugin.json', mcpPath: '.mcp.json' },
  { dir: 'cursor', manifestPath: '.cursor-plugin/plugin.json', mcpPath: 'mcp.json' },
];

for (const target of targets) {
  writeGenerated(target.dir, 'skills/newrelic-commerce/SKILL.md', skillMd);
  writeGenerated(target.dir, 'agents/newrelic-security.md', agentMd);
  writeGenerated(target.dir, 'commands/nrql.md', commandMd);
  writeGenerated(target.dir, target.mcpPath, mcpJson);
  writeGenerated(target.dir, target.manifestPath, manifestJson);
}
