#!/usr/bin/env node
/**
 * Generates the installable Cursor plugin (skill + agent + command + mcp.json)
 * under plugins/cursor/ from the canonical prompt/server sources in mcps/newrelic
 * and the repo's own package.json / .mcp.json, so the plugin content never
 * drifts out of sync with the MCP server it wraps.
 *
 * Run: npm run build:plugin:cursor
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { commercePrompt } from '../../mcps/newrelic/prompts/commerce.js';
import { securityPrompt } from '../../mcps/newrelic/prompts/security.js';

const pluginDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(pluginDir, '..', '..');

const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));
const rootMcp = JSON.parse(readFileSync(join(repoRoot, '.mcp.json'), 'utf8'));

const GENERATED_NOTICE =
  '<!-- Generated by plugins/cursor/build.ts — do not edit by hand. Run `npm run build:plugin:cursor`. -->\n\n';

function writeGenerated(relPath: string, content: string): void {
  const fullPath = join(pluginDir, relPath);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content, 'utf8');
  console.log(`plugins/cursor/${relPath}`);
}

function markdownFile(fields: Record<string, string>, body: string): string {
  const frontmatter = Object.entries(fields)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join('\n');
  return `---\n${frontmatter}\n---\n\n${GENERATED_NOTICE}${body.trim()}\n`;
}

writeGenerated(
  'skills/newrelic-commerce/SKILL.md',
  markdownFile(
    {
      name: 'newrelic-commerce',
      description:
        'New Relic NRQL specialist for Adobe Commerce and general querying. Resolves Adobe Commerce project IDs to New Relic account IDs and runs NRQL queries against Log, Transaction, APM, Redis, MySQL, and Elasticsearch data.',
    },
    commercePrompt,
  ),
);

writeGenerated(
  'agents/newrelic-security.md',
  markdownFile(
    {
      name: 'newrelic-security',
      description:
        'New Relic security analyst for Adobe Commerce. Detects and investigates attacks (brute force, SQL injection, XSS, DDoS, scraping, carding, API abuse) using NRQL queries.',
    },
    securityPrompt,
  ),
);

writeGenerated(
  'commands/nrql.md',
  markdownFile(
    {
      name: 'nrql',
      description: 'Run an ad-hoc NRQL query against New Relic for an Adobe Commerce project.',
    },
    [
      'Run the NRQL query below against New Relic.',
      '',
      '1. If given an Adobe Commerce project ID instead of an account ID, call `get_account_id_by_project_id` first and use the returned account ID.',
      '2. Execute the query with the `execute_nrql` tool.',
      '3. Summarize the result set: row count, key fields, and any errors.',
      '',
      'For field-discovery rules and standard Adobe Commerce entity filters, invoke the `newrelic-commerce` skill first.',
      '',
      'Query:',
      '$ARGUMENTS',
    ].join('\n'),
  ),
);

writeGenerated(
  'mcp.json',
  `${JSON.stringify({ mcpServers: { newrelic: rootMcp.mcpServers.newrelic } }, null, 2)}\n`,
);

writeGenerated(
  '.cursor-plugin/plugin.json',
  `${JSON.stringify(
    {
      name: 'newrelic-nrql',
      description: pkg.description,
      version: pkg.version,
      homepage: pkg.homepage,
      license: pkg.license,
    },
    null,
    2,
  )}\n`,
);
